// Export as `Products` (capital) to match imports elsewhere
export const Products = [
    {
        id: 1,
        images: ["./src/assets/new1.png"],
        title: "T-shirt with Tape Details",
        name: "T-shirt with Tape Details",
        rating: 4.5,
        price: 120,
    },
    {
        id: 2,
        images: ["./src/assets/new2.png"],
        title: "Skinny Fit Jeans",
        name: "Skinny Fit Jeans",
        rating: 3.5,
        price: 240,
        oldPrice: 260,
    },
    {
        id: 3,
        images: ["./src/assets/new3.png"],
        title: "Checkered Shirt",
        name: "Checkered Shirt",
        rating: 4.5,
        price: 180,
    },
    {
        id: 4,
        images: ["./src/assets/new4.png"],
        title: "Sleeve Striped T-shirt",
        name: "Sleeve Striped T-shirt",
        rating: 4.5,
        price: 130,
        oldPrice: 160,
    },
    {
        id: 5,
        images: ["./src/assets/top1.png"],
        title: "Vertical Striped Shirt",
        name: "Vertical Striped Shirt",
        rating: 5.0,
        price: 212,
        oldPrice: 232,
    },
    {
        id: 6,
        images: ["./src/assets/top2.png"],
        title: "Courage Graphic T-shirt",
        name: "Courage Graphic T-shirt",
        rating: 4.0,
        price: 145,
    },
    {
        id: 7,
        images: ["./src/assets/top3.png"],
        title: "Loose Fit Bermuda Shorts",
        name: "Loose Fit Bermuda Shorts",
        rating: 3.0,
        price: 80,
    },
    {
        id: 8,
        images: ["./src/assets/top4.png"],
        title: "Faded Skinny Jeans",
        name: "Faded Skinny Jeans",
        rating: 4.5,
        price: 210,
    },
    {
        id: 9,
        images: ["./src/assets/you1.png"],
        title: "Polo with Contrast Trims",
        name: "Polo with Contrast Trims",
        rating: 4.0,
        price: 212,
        oldPrice: 242,
    },
    {
        id: 10,
        images: ["./src/assets/you2.png"],
        title: "Gradient Graphic T-shirt",
        name: "Gradient Graphic T-shirt",
        rating: 3.5,
        price: 145,
    },
    {
        id: 11,
        images: ["./src/assets/you3.png"],
        title: "Polo with Tipping Details",
        name: "Polo with Tipping Details",
        rating: 4.5,
        price: 180,
    },
    {
        id: 12,
        images: ["./src/assets/you4.png"],
        title: "Black Striped T-shirt",
        name: "Black Striped T-shirt",
        rating: 5.0,
        price: 120,
        oldPrice: 150,
    },
    {
        id: 13,
        image: "./src/assets/you4.png",
        images: [
            "/src/assets/one1.png",
            "/src/assets/one2.png",
            "/src/assets/one3.png",
        ],
        title: "One Life Graphic T-shirt",
        name: "One Life Graphic T-shirt",
        rating: 4.5,
        discount: "-40%",
        price: 260,
        oldPrice: 300,
        sizes: ["Small", "Medium", "Large", "X-Large"],
        colors: ["#474731", "#1f3b3a", "#2c2f63"],
        description:
            "This graphic t-shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    },
];